# Generated by Django 2.0 on 2019-07-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('telugu', models.IntegerField()),
                ('english', models.IntegerField()),
                ('maths', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrationForm',
        ),
    ]
