# Generated by Django 2.0 on 2019-07-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='rollno',
            field=models.CharField(max_length=10),
        ),
    ]
